CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,           
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_username ON users(username);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS name VARCHAR(255);

